### ISSUE TITLE
is working

### ISSUE THREAD

**Issue by joseska** [ozdemirburak/skyscanner-php#1]
Hi... we are trying to use your API, but not work. 
my code is:
require 'vendor/autoload.php';

use OzdemirBurak\SkyScanner\Travel\Flights\LivePricing;

$pricing = new LivePricing($apiKey = 'mr724683266549xxxxxxxxxxx', $country = 'GB', $currency = 'EUR', $locale = 'en-GB');
$pricing->setParameters([
    'adults' => 1,
    'destinationplace' => 'IST',
    'originplace' => 'LHR',
    'outbounddate' => '10/10/2016',
    'stops' => 0
]);
$flights = $pricing->parseFlights($onlyCheapestAgentPerItinerary = true);

var_dump($flights);

**Comment by ozdemirburak** [comment]
Hi, can you check the response code like below and write the output.

```
$flights = $pricing->parseFlights($onlyCheapestAgentPerItinerary = true);
var_dump($pricing->getResponseStatus());
```

You can also check the response codes and their meanings [here](https://github.com/ozdemirburak/skyscanner-php/blob/master/src/BaseRequest.php#L187).

**Comment by joseska** [comment]
When I execute the php file (111.php) always try to download my php file....it's strange

**Comment by ozdemirburak** [comment]
After having a look at your first message again, I suppose I know what's causing the error. Outbound date should be in the format of 'Y-m-d'. What your format is 'd/m/Y' or 'm/d/Y'.

You should pass the `outbounddate` variable as **2016-10-10** for the query above.

```
$pricing->setParameters([
    'adults' => 1,
    'destinationplace' => 'IST',
    'originplace' => 'LHR',
    'outbounddate' => '2016-10-10',
    'stops' => 0
]);
```

**Comment by ozdemirburak** [comment]
Closing as hoping that you've resolved your issue. If not, don't hesitate to reopen this ticket.
