### ISSUE TITLE
Places and stops not available in the result

### ISSUE THREAD

**Issue by DDholiyan** [ozdemirburak/skyscanner-php#2]
Hi I am using your code for fetching results in my coding style. This is good and written in better way. 
Please tell me how can I embed places and stops in the returning result.

Thanks

**Comment by DDholiyan** [comment]
I just pass new key pair in $legVariables like 'stops'=>'Stops'. Now I am getting stops.
But Please tell me how can I display places name for origin/destination and stops.

**Comment by ozdemirburak** [comment]
Just to be clear, this is about LivePricing right? Furthermore, you want to display all the places which is actually returned by the initial request?

**Comment by DDholiyan** [comment]
yes, like origin, destination and stops places. In current this returns places code.

Thanks

**Comment by ozdemirburak** [comment]
@DDholiyan Hi sorry for the really late update. I've upgraded the code. You can get all using the `get()` method. 

If you call get method without any parameters, it will return all the data provided by API without any modification.

However, if you only want to get places, then something like below will help you.

```php
use OzdemirBurak\SkyScanner\Travel\Flights\LivePricing;

$pricing = new LivePricing($apiKey = 'your-api-key', $country = 'GB', $currency = 'GBP', $locale = 'en-GB');
$pricing->setParameters([
    'adults' => 1,
    'destinationplace' => 'IST',
    'originplace' => 'LHR',
    'outbounddate' => date('Y-m-d', strtotime('+1 week')),
    'stops' => 0
]);
$places = $pricing->get('Places');
```

Please, feel free to reopen this issue if you face with any issues.
