### ISSUE TITLE
Reuse of BrowseCache class instance is impossible, because of Unset variables in addQuotes function

### ISSUE THREAD

**Issue by pich** [ozdemirburak/skyscanner-php#4]
Hardcoded "protected $removeIds = true;" in TravelService results in impossibility of call getPrices more than once. Undefined property: stdClass::$CarrierIds occurs.

**Comment by ozdemirburak** [comment]
I may be missing an use-case scenario for this but why do you call it more than once without storing it in a variable?

But anyway, I'm setting the `removeIds` property to false by default.

**Comment by ozdemirburak** [comment]
Closing this, if you still have any questions and issues, I'm here to assist.
