### ISSUE TITLE
Stops parameter

### ISSUE THREAD

**Issue by Qkin** [ozdemirburak/skyscanner-php#5]
In LivePricing class there is a 'stop' parameter set as 0 by default. Based on API documentacion this param can  be only 0 or 1, but if you don't want to get results depending on stops, you shouldn't send this param at all. You should set $stop property as null by default and do not return it in getOptionalPollingParameters() method if there is no value in it.

**Comment by ozdemirburak** [comment]
Thanks for reporting this, feel free to send a pull request to fix this issue.

**Comment by LiamNorman** [comment]
Hey I'd like to look into this if it's still an issue?

**Comment by ozdemirburak** [comment]
@LiamNorman Sure.
