### ISSUE TITLE
Hotels Live Prices

### ISSUE THREAD

**Issue by ozdemirburak** [ozdemirburak/skyscanner-php#6]
Hotels Live Prices service is missing. One can implement it with the help of the [API documentation](
https://skyscanner.github.io/slate/#hotels-live-prices).

**Comment by johnflah** [comment]
Hi I would enjoy taking this one if still available. 

Regards,

John

**Comment by ozdemirburak** [comment]
Sure, thanks!

**Comment by johnflah** [comment]
No problem , I've registered with skyscanner to get api access, i can work away through docs in the mean time.
