### ISSUE TITLE
Undefined index: argv

### ISSUE THREAD

**Issue by jamesmills** [ozdemirburak/skyscanner-php#9]
Undefined index: argv

vendor/ozdemirburak/skyscanner-php/src/Traits/ConsoleTrait.php (114)

```
    private function isPrintable($force = true): bool
    {
        return !($force === false && strpos($_SERVER['argv'][0], 'phpunit') !== false);
    }
```

Might need to rewrite this as

```
return !($force === false && strpos(($_SERVER['argv'][0]) ?? null, 'phpunit') !== false);
```

**Comment by ozdemirburak** [comment]
Hi James, thanks for bringing this issue. Would you send a PR or should I patch this?

**Comment by jamesmills** [comment]
I pushed a patch :-)

**Comment by ozdemirburak** [comment]
Thank you very much, appreciated :)
